services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MOODLE_MIDDLEWARE_HOST=${SERVER_HOST}:${SERVER_PORT} # Replace with your middleware IP
    volumes:
      - moodledata:/var/www/html/moodledata
    ports:
      - "${MOODLE_PORT}:80"
    depends_on:
      - moodle_db
  
  moodle_db:
    image: mariadb:latest
    restart: always
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
      - ./config/moodle/db-setup:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_DB_PORT}:${MYSQL_DB_PORT}"
  
  server:
    image: padimaster/moodle-push
    container_name: server
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - server_db
  server_db:
    image: postgres
    container_name: server_database
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  moodledata:
  dbdata:
  pgdata:
